In [4]:
import numpy as np
import scipy.stats as spst
from scipy.optimize import leastsq
import pandas as pd

In [60]:
mizon57= pd.read_csv("Mizon57.csv")

In [61]:

mizon57["L"]= (mizon57["LF"]-mizon57["U"])*mizon57["H"]/100
mizon57["L100"]= (mizon57["LF"]-mizon57["U"])*mizon57["H"]

In [62]:
mizon57

Q     K    LF   U   H       L   L100
0    405   335   605   9  47  280.12  28012
1    245   130   202   2  46   92.00   9200
2     31   100    19   0  48    9.12    912
3     37   191    37   0  48   17.76   1776
4    526   615   459   4  47  213.85  21385
5    430   504   404   4  48  192.00  19200
6     88    63    70   1  47   32.43   3243
7    130    98   133   1  47   62.04   6204
8   1558   758  1940  16  47  904.28  90428
9    221    58   318   6  48  149.76  14976
10   365   270   411   6  46  186.30  18630
11   273   140   303   1  47  141.94  14194
12    94    44   160   0  48   76.80   7680
13   404   197   517   6  45  229.95  22995
14   605   589  1015  15  44  440.00  44000
15   308    82   681  10  41  275.11  27511
16   184   105   195   2  50   96.50   9650
17    91    48   147   3  45   64.80   6480
18   184    54   289   5  45  127.80  12780
19   503   356   571   4  45  255.15  25515
20   189   133   282   4  46  127.88  12788
21  1124   252  1466  39  49  699.23  69923
22   127   309   142   1  47   66.27   6627
23   290  1810   211   1  48  100.80  10080

In [191]:
def sse_ces(params, X_data,Y_data):
    """Sum of squared error
    Q = \gamma[\delta K^{-\rho} +(1-\delta) L^{-\rho}  ]^{-\frac{\nu}{\rho}
    error = Q_est - Q
    """
    Q = Y_data[:,0]
    K = X_data[:,0]
    L = X_data[:,1]    
    gamma = params[0]
    delta = params[1]
    rho = params[2]
    nu = params[3]
    Q_est =  gamma*(delta* K**(-rho) + (1-delta)* L**(-rho))**(-nu/rho)
    return  np.array(Q - Q_est)
    


In [192]:
P0 = np.array([0.1, 0.1, -0.1, 1.0])

estimates = leastsq(sse_ces, P0, args = ( np.array(mizon57.ix[:,["K","L100"]]), np.array(mizon57.ix[:,["Q"]]) ), full_output=1)

estimates


(array([ 0.04746368,  0.43092672, -0.34408368,  1.02076229]),
 array([[  2.70092148e-07,   2.31962255e-06,  -2.30251548e-06,
          -1.60781575e-07],
        [  2.31962255e-06,   3.04640428e-05,  -3.00178039e-05,
           6.06735240e-07],
        [ -2.30251548e-06,  -3.00178039e-05,   3.11229845e-05,
          -2.61628256e-07],
        [ -1.60781575e-07,   6.06735240e-07,  -2.61628256e-07,
           5.30247922e-07]]),
 {'fjac': array([[  5.01939387e+04,   6.71009686e-02,   9.65722114e-03,
            1.89701046e-02,   1.78940605e-01,   1.57629428e-01,
            2.43497267e-02,   4.56598802e-02,   6.42567027e-01,
            9.37336601e-02,   1.38417957e-01,   9.91851137e-02,
            4.94793836e-02,   1.59271728e-01,   3.28823736e-01,
            1.69925305e-01,   6.78111670e-02,   4.29106026e-02,
            8.04532754e-02,   1.89714153e-01,   8.98203197e-02,
            4.48575821e-01,   5.95956123e-02,   1.29068935e-01],
         [  2.29327207e+04,  -1.49907848e+03,   5.3

In [205]:

func = sse_ces
name = "CES production function" 
                 
#p0= {"gamma": 0.04746368, "delta":0.43092672,"rho": -0.34408368, "nu": 1.020762290}
#p0= {"gamma": 0.18, "delta":0.1,"rho": -0.1, "nu": 1.01}



xdata= np.array(mizon57.ix[:,["K","L100"]])
ydata= np.array(mizon57.ix[:,["Q"]])
inits = list(p0.values()) 

#https://stackoverflow.com/questions/9219094/order-of-values-when-extracting-python-dict-to-list

In [ ]:
params = ["gamma", "delta","rho", "nu"]
#p0 =np.array([0.04746368, 0.43092672,-0.34408368,  1.020762290])
p0 =np.array([0.1, 0.1,-0.1,  1.1])

In [202]:
# Run the model
mod1 = leastsq(sse_ces, p0, args = (xdata, ydata), full_output=1)


In [203]:
mod1

(array([ 0.04746368,  0.43092672, -0.34408368,  1.02076229]),
 array([[  2.70092148e-07,   2.31962255e-06,  -2.30251548e-06,
          -1.60781575e-07],
        [  2.31962255e-06,   3.04640428e-05,  -3.00178039e-05,
           6.06735240e-07],
        [ -2.30251548e-06,  -3.00178039e-05,   3.11229845e-05,
          -2.61628256e-07],
        [ -1.60781575e-07,   6.06735240e-07,  -2.61628256e-07,
           5.30247922e-07]]),
 {'fjac': array([[  5.01939387e+04,   6.71009686e-02,   9.65722114e-03,
            1.89701046e-02,   1.78940605e-01,   1.57629428e-01,
            2.43497267e-02,   4.56598802e-02,   6.42567027e-01,
            9.37336601e-02,   1.38417957e-01,   9.91851137e-02,
            4.94793836e-02,   1.59271728e-01,   3.28823736e-01,
            1.69925305e-01,   6.78111670e-02,   4.29106026e-02,
            8.04532754e-02,   1.89714153e-01,   8.98203197e-02,
            4.48575821e-01,   5.95956123e-02,   1.29068935e-01],
         [  2.29327207e+04,  -1.49907848e+03,   5.3

In [225]:
# Get the parameters
parmEsts = np.round( mod1[0], 4 )

# Get the Error variance and standard deviation
RSS = np.sum( mod1[2]['fvec']**2 )
df = nobs - nparm
MSE = RSS / df
RMSE = np.sqrt( MSE )

# Get the covariance matrix
cov = MSE * mod1[1]

# Get parameter standard errors
parmSE = np.diag( np.sqrt( cov ) )

# Calculate the t-values
tvals = parmEsts/parmSE

# Get p-values
pvals = (1 - spst.t.cdf( np.abs(tvals), df))*2

# Get biased variance (MLE) and calculate log-likehood
s2b = RSS / nobs
logLik = -nobs/2 * np.log(2*np.pi) - nobs/2 * np.log(s2b) - 1/(2*s2b) * RSS

#del(mod1)
#del(s2b)
#del(inits)

# Get AIC. Add 1 to the df to account for estimation of standard error
def AIC(self, k=2):
    return -2*logLik + k*(nparm + 1)



/opt/conda/lib/python3.5/site-packages/ipykernel/__main__.py:14: RuntimeWarning: invalid value encountered in sqrt


In [226]:
# Print the summary
def summary():
    print()
    print( 'Non-linear least squares')
    print( 'Model: ' + name)
    print( 'Parameters:')
    print( " Estimate Std. Error t-value P(>|t|)")
    for i in range( len(parmNames) ):
            print( "% -5s % 5.4f % 5.4f % 5.4f % 5.4f" % tuple( [parmNames[i], 
                                                                parmEsts[i], parmSE[i], tvals[i], pvals[i]] ))
    print()
    print( 'Residual Standard Error: % 5.4f' % RMSE)
    print( 'Df: %i' % df)
summary()


Non-linear least squares
Model: CES production function
Parameters:
 Estimate Std. Error t-value P(>|t|)
rho    0.0475  0.0332  1.4327  0.1674
delta  0.4309  0.3521  1.2238  0.2353
nu    -0.3441  0.3559 -0.9668  0.3452
gamma  1.0208  0.0465  21.9741  0.0000

Residual Standard Error:  63.7954
Df: 20


## Very sensitive for initial value

In [216]:
# modified to fit python3.5
# # #  https://www.r-bloggers.com/r-vs-python-practical-data-analysis-nonlinear-regression/


class NLS:
    ''' This provides a wrapper for scipy.optimize.leastsq to get the relevant output for nonlinear least squares.
    Although scipy provides curve_fit for that reason, curve_fit only returns parameter estimates and covariances. 
    This wrapper returns numerous statistics and diagnostics'''
 
    import numpy as np
    import scipy.stats as spst
    from scipy.optimize import leastsq
 
    def __init__(self,func,name, params ,p0, xdata, ydata):
        """
        func: error function y^ - y
        name: model name
        params: names of parameters, list
        p0: starting value for params(the same order), np.array
        xdata: np.array 
        ydata: np.array
        
        """
        # Check the data     
        
        if len(xdata) != len(ydata):
            msg = 'The number of observations does not match the number of rows for the predictors'
            raise ValueError(msg)
 

            
        self.name = name 
        self.func = func

        self.xdata = xdata
        self.ydata = ydata
        
        self.nobs = len( ydata )

        # Check parameter estimates
#         if type(p0) != dict:
#             msg = "Initial parameter estimates (p0) must be a dictionry of form p0={'a':1, 'b':2, etc}"
#             raise ValueError(msg)
        
        self.inits = p0 
        self.nparm= len( self.inits )
        self.parmNames = params
        
        # clean parameters' names 
        for i in range( len(self.parmNames) ):
            if len(self.parmNames[i]) > 5:
                self.parmNames[i] = self.parmNames[i][0:4]
 
        # Run the model
        self.mod1 = leastsq(self.func, np.array(self.inits), args = (self.xdata, self.ydata), full_output=1)
 
        # Get the parameters
        self.parmEsts = np.round( self.mod1[0], 4 )
 
        # Get the Error variance and standard deviation
        self.RSS = np.sum( self.mod1[2]['fvec']**2 )
        self.df = self.nobs - self.nparm
        self.MSE = self.RSS / self.df
        self.RMSE = np.sqrt( self.MSE )
 
        # Get the covariance matrix
        self.cov = self.MSE * self.mod1[1]
 
        # Get parameter standard errors
        self.parmSE = np.diag( np.sqrt( self.cov ) )
 
        # Calculate the t-values
        self.tvals = self.parmEsts/self.parmSE
 
        # Get p-values
        self.pvals = (1 - spst.t.cdf( np.abs(self.tvals), self.df))*2
 
        # Get biased variance (MLE) and calculate log-likehood
        self.s2b = self.RSS / self.nobs
        self.logLik = -self.nobs/2 * np.log(2*np.pi) - self.nobs/2 * np.log(self.s2b) - 1/(2*self.s2b) * self.RSS
 
        #del(self.mod1)
        #del(self.s2b)
        #del(self.inits)
 
    # Get AIC. Add 1 to the df to account for estimation of standard error
    def AIC(self, k=2):
        return -2*self.logLik + k*(self.nparm + 1)
 
    del(np)
    del(leastsq)
 
    # Print the summary
    def summary(self):
        print()
        print( 'Non-linear least squares')
        print( 'Model: ' + self.name)
        print( 'Parameters:')
        print( " Estimate Std. Error t-value P(>|t|)")
        for i in range( len(self.parmNames) ):
                print( " % -5s % 5.4f % 5.4f % 5.4f % 5.4f" % tuple( [self.parmNames[i], 
                                                                    self.parmEsts[i], self.parmSE[i], self.tvals[i], self.pvals[i]] ))
        print()
        print( 'Residual Standard Error: % 5.4f' % self.RMSE)
        print( 'Df: %i' % self.df)


In [222]:
params = ["gamma", "delta","rho", "nu"]
#p0 =np.array([0.04746368, 0.43092672,-0.34408368,  1.020762290])
p0 =np.array([0.1, 0.1,-0.1,  1.1])

nls_mizon57 = NLS(func = sse_ces,name = "CES production function", params = params,
                  p0=p0, xdata= np.array(mizon57.ix[:,["K","L100"]]), ydata= np.array(mizon57.ix[:,["Q"]]))

/opt/conda/lib/python3.5/site-packages/ipykernel/__main__.py:70: RuntimeWarning: invalid value encountered in sqrt


In [223]:
nls_mizon57.summary()


Non-linear least squares
Model: CES production function
Parameters:
 Estimate Std. Error t-value P(>|t|)
gamma  0.0475  0.0332  1.4329  0.1673
delta  0.4309  0.3521  1.2238  0.2353
rho   -0.3441  0.3559 -0.9668  0.3452
nu     1.0208  0.0465  21.9741  0.0000

Residual Standard Error:  63.7954
Df: 20


In [ ]:
# stnd    = input(r'P ($\%$) and $\theta$ of pol. standard? (as tuple)')
# p       = stnd[0]/100.
# ang     = np.radians(stnd[1])  
# x,y     = sympy.symbols('x y')  
# stndqu  = sympy.solve([sympy.sqrt(x**2+y**2)-p,(0.5*sympy.atan(y/x))-ang],[x,y])[1] 

# stndqun = np.array([sympy.N(i) for i in stndqu],dtype=float) 




